version: '3'

services:

  client:
    image: curso.client
    build: ./client
    volumes:
    - ./client:/app

  serverApi:
    image: curso.api
    build: 
      context: ./server/src/Eventos.IO.Services.Api
      dockerfile: Dockerfile.prod
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production

  nginx:
    image: curso.proxy
    build: ./nginx
    ports:
      - "80:80"
      - "8287:8286"
    links:
      - client
      - serverApi